services:
  web:
    build: 
      context: ./services/web
      dockerfile: Dockerfile.prod
    command: waitress-serve --url-prefix='/infoscreen' --call "infoscreen:create_app"
    expose:
      - 8080
    env_file:
      - ./.env.dev

  wiki:
    build: 
      context: ./services/wiki
      dockerfile: Dockerfile
    command: waitress-serve --url-prefix='/wiki' "manage:application"
    expose:
      - 8080
    env_file:
      - ./.env.dev

  nginx:
    build: ./services/nginx
    ports:
      - 1337:80
    depends_on:
      - web
      - wiki
